Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,16 +38,14 @@ jobs:
       - name: Prepare sample data
         run: |
           mkdir -p data
-          if [ ! -f data/sample_signal.csv ]; then
-           if [ -f demo/sample_signal.csv ]; then
-            cp demo/sample_signal.csv data/sample_signal.csv
-           else
-            echo "ERROR: demo/sample_signal.csv not found!"
-            exit 1
-            fi
+          if [ -f demo/sample_signal.csv ]; then
+           cp demo/sample_signal.csv data/sample_signal.csv
+           echo "Sample CSV copied successfully."
           else
-           echo "Sample CSV already exists"
+           echo "ERROR: demo/sample_signal.csv not found!"
+           exit 1
           fi
+
 
 
 
